sudo: required
dist: trusty
services:
- docker
addons:
  apt:
    packages:
    - nodejs
    - npm
language: java
jdk:
- oraclejdk8
install:
- npm install -g dockerfile_lint
before_script:
- dockerfile_lint -f src/main/docker/Dockerfile
script:
- docker build --tag garethahealy/base-java-docker:latest src/main/docker/
cache:
  directories:
  - $HOME/.m2
