sudo: required
dist: trusty
services:
- docker
language: node_js
node_js:
- "node"
- "8"
install:
- npm install -g dockerfile_lint
before_script:
- dockerfile_lint -f Dockerfile
script:
- docker build --tag garethahealy/base-java-docker:latest .
