sudo: required
services:
  - docker
before_install:
  - docker build --tag garethahealy/base-java-docker:latest src/main/docker/
language: java
install: mvn clean install -Dgpg.skip=true
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
